spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      initialize: true
      url: jdbc:log4jdbc:mariadb://localhost:3306/cloudbridge
      username: cloudbridge
      password: Rlagytjq!2
      validation-query: SELECT 1
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      
  jpa:
    hibernate: 
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  h2:
    console:
      enable: true
      path: /h2
      
      
 #h2 DB세팅
 #spring
   #datasource
    #initialize: true
    #url: jdbc:h2:~/my-slipp
    #username: sa
    #password: 
    #validation-query: SELECT 1
    #driver-class-name: org.h2.Driver
  #jpa
    #database-platform: org.hibernate.dialect.H2Dialect