spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      url: jdbc:log4jdbc:mariadb://localhost:3306/cloudbridge
      username: cloudbridge
      password: Rlagytjq!2
      validation-query: SELECT 1
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate: 
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    database: mysql
