INSERT INTO MEMBER(ID, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD) VALUES (1, 'javajigi', '자바지기', 'test');
INSERT INTO MEMBER(ID, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD) VALUES (2, 'sanjigi', '산지기', 'test');

INSERT INTO QUESTION(ID, CONTENTS, CREATE_DATE, TITLE, WRITER_ID) VALUES (1, '자바지기', CURRENT_TIME, '자바지기',1);
INSERT INTO QUESTION(ID, CONTENTS, CREATE_DATE, TITLE, WRITER_ID) VALUES (2, '산지기', CURRENT_TIME, '산지기',2); 
