INSERT INTO MEMBER(ID, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, CREATE_DATE) VALUES (1, 'javajigi', '자바지기', 'test', CURRENT_TIME);
INSERT INTO MEMBER(ID, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, CREATE_DATE) VALUES (2, 'sanjigi', '산지기', 'test', CURRENT_TIME);

INSERT INTO QUESTION(ID, CONTENTS, COUNT_OF_ANSWER, CREATE_DATE, TITLE, WRITER_ID) VALUES (1, '자바지기', 0, CURRENT_TIME, '자바지기',1);
INSERT INTO QUESTION(ID, CONTENTS, COUNT_OF_ANSWER, CREATE_DATE, TITLE, WRITER_ID) VALUES (2, '산지기', 0, CURRENT_TIME, '산지기',2); 